CI(publish): stop using cache & "npm ci"
The cache was the reason that the publish job failed the
last time it was run with this error:

```
Error: Dependencies lock file is not found in /home/runner/work/fp-sdk/fp-sdk. Supported file patterns: package-lock.json,npm-shrinkwrap.json,yarn.lock
```

And the the "npm ci" build style with this error:
```
The `npm ci` command can only install with an existing package-lock.json or...
````

This should have been done in:
218db00d205013352e267acbb9f2210c03b76297